services:
  postgres:
    image: postgres:17
    container_name: oficina-postgres
    restart: always
    environment:
      POSTGRES_USER: oficina_user
      POSTGRES_PASSWORD: oficina_pass
      POSTGRES_DB: oficina_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: