apiVersion: v1
kind: Service
metadata:
  name: oficina-api
  namespace: oficina
  labels:
    app: oficina-api
spec:
  selector:
    app: oficina-api
  ports:
    # NodePort 30080 maps to host port defined in Kind extra_port_mappings (var.app_host_port, default 3000)
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort
